name: Saludo usando variables
run-name: Â¡Estoy aprendiendo a usar Variables!
on: [push]
env:
  DIA_DE_SEMANA: Martes
jobs:
  saludo-variables:
    runs-on: ubuntu-latest
    env:
      SALUDO: Jelou
    steps:
      - name: Saludar
        run: echo "$SALUDO, $NOMBRE. Hoy es $DIA_DE_SEMANA! $SALUDO"
        env:
          NOMBRE: Daniel
